wordpress_name: wordpress
wordpress_image_name: wordpress
wordpress_image_version: latest
wordpress_image: "{{ wordpress_image_name }}:{{ wordpress_image_version }}"
wordpress_db_name: wordpress-mysql
wordpress_db_pass_secret_name: "{{ wordpress_db_name }}-root-pass"
wordpress_db_pass_secret_key: root_password
wordpress_external_port: 30180
wordpress_storage_class: local-storage
wordpress_storage_request: 10Gi
wordpress_rollout_retries: 10
wordpress_rollout_delay: 5
