- name: Create Wordpress resources
  command: kubectl apply -f -
  args:
    stdin: "{{ lookup('template', item + '.yaml.j2') }}"
  register: deploy_wordpress_svc_results
  changed_when: >-
    deploy_wordpress_svc_results.stdout_lines
      | reject('match', '^.* unchanged$') | list | length > 0
  loop:
  - wordpress_pvc
  - wordpress_deployment
  - wordpress_svc
  notify:
  - Wait for Wordpress service to roll out
