- name: Deploy MySQL server
  command: kubectl apply -f -
  args:
    stdin: "{{ lookup('template', item + '.yaml.j2') }}"
  vars:
    mysql_root_password: >-
      {{ lookup('password', 'mysql_root_pass chars=ascii_letters,digits') }}
  loop:
  - mysql_root_pass
  - mysql_statefulset
  - mysql_svc
  register: mysql_deploy_result
  changed_when: >-
    mysql_deploy_result.stdout_lines
      | reject('match', '^.* unchanged$') | list | length > 0
  notify:
  - Wait for MySQL database to roll out
